# Generated by Django 3.1.4 on 2020-12-07 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemChoice',
            fields=[
                ('choice_id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=500)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subscale',
            fields=[
                ('subscale_id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_ip', models.CharField(max_length=500)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=500)),
                ('subscale_id', models.ForeignKey(db_column='subscale_id', on_delete=django.db.models.deletion.CASCADE, to='testroom.subscale')),
            ],
        ),
    ]
