# Generated by Django 3.1.4 on 2020-12-07 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testroom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='subscale_id',
        ),
    ]
