# Generated by Django 3.1.4 on 2020-12-08 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testroom', '0002_remove_item_subscale_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='value',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='TestItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_id', models.ForeignKey(db_column='choice_id', on_delete=django.db.models.deletion.CASCADE, to='testroom.itemchoice')),
                ('item_id', models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, to='testroom.item')),
                ('test_id', models.ForeignKey(db_column='test_id', on_delete=django.db.models.deletion.CASCADE, to='testroom.test')),
            ],
        ),
    ]
