# Generated by Django 3.1.4 on 2020-12-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testroom', '0004_auto_20201209_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
